import Head from "next/head";
import { useState } from "react";
import Navbar from "../components/Navbar";
import Editor from "@monaco-editor/react";
import axios from "axios";

export default function Home() {
  const [code, setCode] = useState("");
  const [lang, setLang] = useState("py");
  const [theme, setTheme] = useState("light");
  const [fontsize, setFontsize] = useState(20);
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");
  const [loading, setLoading] = useState(false);
  const options = { fontSize: fontsize };

  const compile = () => {
    setLoading(true);
    if (code === "") {
      return;
    }
    axios
      .post("/api/compile", { code, lang, input })
      .then((response) => {
        setOutput(response.data.output);
      })
      .then(() => {
        setLoading(false);
      });
  };

  return (
    <div>
      <Head>
        <title>coderx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col w-screen h-screen ">
        <div className="h-1/8">
          <Navbar
            lang={lang}
            setLang={setLang}
            theme={theme}
            setTheme={setTheme}
            compile={compile}
          />
        </div>

        <div className="flex flex-col md:flex-row md:h-screen">
          <div className="w-screen h-4/5 md:w-2/3 md:h-full">
            <Editor
              height="100%"
              width="100%"
              theme={theme}
              language={lang}
              defaultLanguage="python"
              defaultValue="# Enter your code here"
              onChange={(value) => {
                setCode(value);
              }}
            />
          </div>
          <div className="flex flex-row h-1/5 w-screen md:w-1/3 md:flex-col md:h-full">
            <div>
              <lable>input</lable>
              <textarea
                className="textarea textarea-bordered w-full h-full md:h-24"
                placeholder="Input"
                value={input}
                onChange={(e) => {
                  setInput(e.target.value);
                }}
              ></textarea>
            </div>
            <div>
              <label>output</label>
              <textarea
                className="textarea textarea-bordered w-full h-full md:h-24"
                placeholder="Output"
                value={output}
                onChange={(e) => {
                  setOutput(e.target.value);
                }}
              ></textarea>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
